### ISSUE TITLE
Template Override for Action Replaces Frontend Template

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/KanboardEmailHistory#1]
The template override in the `plugin.php`
```
$this->template->setTemplateOverride('task_comments/show', 'kanboardEmailHistory:task_comments/show');
```
conflicts with the task page (comments section). Struggling to understand how to code it in such a way that the front end is working as normal and only for the action, we use this new template.

**Comment by creecros** [comment]
did you get it? I have a screaming headache right now, but I'll take a look when I'm feeling better. I won't leave you hanging.

**Comment by aljawaid** [comment]
@creecros I sorted it, thanks.  Released the first working version.  Seems fine so far, will monitor over a few cronjobs over coming days.

Slowly, I will try to duplicate the Task2PDF style to include the links/attachment list etc to the contents of the email.

**Comment by creecros** [comment]
awesome, great job! if you get stuck, let me know.
