### ISSUE TITLE
Override `params.php` Without Affecting Other Plugins

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/KanboardEmailHistory#15]
> About the core, what if I override the `step 2`?

autosubtasks overrides the `params.php` but what if i override step 2, which is `action_creation/event.php` ? then in that override, we say, if this plugin then process and go to MY params file, otherwise leave it as it is.... this will then be picked up by autosubtasks and overridden.

```php
<div class="page-header">
    <h2><?= t('Choose an event') ?></h2>
</div>

// SO IF WE DO AN `IF` STATEMENT HERE WITH MAYBE A CUSTOM CONTROLLER...
IF ...EXISTS PLUGIN/KANBOARDEMAILHOSTORY
     then duse my controller to send my version of the params file, otherwise....
ELSE... BELOW IS DEFAULT CODE

<form method="post" action="<?= $this->url->href('ActionCreationController', 'params', array('project_id' => $project['id'])) ?>">
    <?= $this->form->csrf() ?>

    <?= $this->form->hidden('action_name', $values) ?>

    <?= $this->form->label(t('Action'), 'action_name') ?>
    <?= $this->form->select('action_name', $available_actions, $values, array(), array('disabled')) ?>

    <?= $this->form->label(t('Event'), 'event_name') ?>
    <?= $this->form->select('event_name', $events, $values) ?>

    <div class="form-help">
        <?= t('When the selected event occurs execute the corresponding action.') ?>
    </div>

    <?= $this->modal->submitButtons(array(
        'submitLabel' => t('Next step')
    )) ?>
</form>
```

_Originally posted by @aljawaid in https://github.com/aljawaid/KanboardEmailHistory/discussions/12#discussioncomment-4689191_

**Comment by aljawaid** [comment]
@creecros please check, I think I am done

- I duplicated the controller into the plugin here (just changed the render to my template)
https://github.com/aljawaid/KanboardEmailHistory/blob/master/Controller/EmailHistoryController.php 

- Created the `if` statement for the override template here
https://github.com/aljawaid/KanboardEmailHistory/blob/master/Template/action_creation/event.php
https://github.com/aljawaid/KanboardEmailHistory/blob/19a9898299944fa48eccca4a9c6dd4cd16352850/Template/action_creation/event.php#L5
- then I referenced my controller of the duplicate code here
https://github.com/aljawaid/KanboardEmailHistory/blob/19a9898299944fa48eccca4a9c6dd4cd16352850/Template/action_creation/event.php#L6

**Comment by aljawaid** [comment]
oh crap, after doing all this work I think I have messed up...!

- What's the alternative for `file_exists` ? Because, if installed it will exist, but that will mean that Autosubtasks (installed) wont be able to override template at all... I need something like 'if this plugin is being used to access this action'
- also, i tried resetting the param file because the project identifier checkbox in the options is shown as a select list of the projects... i think that has something to do with the rendering of my controller but i dont know where to look.
- the placeholder works/shows up but with `file_exists` I fear it will show for every plugin and every text box in the action forms if this plugin is installed...

I dunno, my head is messed up now

**Comment by aljawaid** [comment]
![image](https://user-images.githubusercontent.com/10233708/212578937-2348df47-324e-4d81-8cc0-179b20b77c6b.png)
---

- is the last select because i used `'plugin' => 'KanboardEmailHistory'`?
https://github.com/aljawaid/KanboardEmailHistory/blob/1010cfd72fec42b0f625285df5f89891c83e749c/Template/action_creation/event.php#L6

**Comment by creecros** [comment]
> oh crap, after doing all this work I think I have messed up...!
> 
> * What's the alternative for `file_exists` ? Because, if installed it will exist, but that will mean that Autosubtasks (installed) wont be able to override template at all... I need something like 'if this plugin is being used to access this action'
> * also, i tried resetting the param file because the project identifier checkbox in the options is shown as a select list of the projects... i think that has something to do with the rendering of my controller but i dont know where to look.
> * the placeholder works/shows up but with `file_exists` I fear it will show for every plugin and every text box in the action forms if this plugin is installed...
> 
> I dunno, my head is messed up now

it's okay, at least you learned something and got a little practice. 

as for file_exists. I'm not aware of that php method, 'if this plugin is being used to access this action'. maybe in the next php release?

**Comment by creecros** [comment]
ewww...I just thought of it though. I guess it does exist.

**Comment by creecros** [comment]
> ewww...I just thought of it though. I guess it does exist.

opp, never-ending, that won't work.

**Comment by creecros** [comment]
well crap, maybe....ya, I think so.

OK, here's my thought.

include a hidden field in the action...and use that in the check to determine if it is coming from your plugin action. if so, have your controller use your params.php, if not, use normal params.php.

**Comment by aljawaid** [comment]
> well crap, maybe....ya, I think so.
> 
> OK, here's my thought.
> 
> include a hidden field in the action...and use that in the check to determine if it is coming from your plugin action. if so, have your controller use your params.php, if not, use normal params.php.

I have no idea how to do that. Thinking of packing it in.

**Comment by aljawaid** [comment]
> well crap, maybe....ya, I think so.
> 
> OK, here's my thought.
> 
> include a hidden field in the action...and use that in the check to determine if it is coming from your plugin action. if so, have your controller use your params.php, if not, use normal params.php.

Could you explain this a bit more please

**Comment by aljawaid** [comment]
> well crap, maybe....ya, I think so.
> 
> OK, here's my thought.
> 
> include a hidden field in the action...and use that in the check to determine if it is coming from your plugin action. if so, have your controller use your params.php, if not, use normal params.php.

@creecros what would the value be?
`<?= $this->form->hidden('kanboardemailhistory_check', $values) ?>`

**Comment by aljawaid** [comment]
@creecros could i use this for the check?
```php
<?php if ($this->app->checkMenuSelection('ActionController'))
```
so if i do it as mycontroller.. do you think it would work?

**Comment by aljawaid** [comment]
ooooh... I think I might have done it.... testing... standby caller
