### ISSUE TITLE
Installation via Plugin Directory Fails?!

### ISSUE THREAD

**Issue by RainerBielefeld** [aljawaid/KanboardEmailHistory#3]
## My KANBOARD Configuration

*  Application version: 1.2.20
* PHP version: 7.4.30
*  PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux 4.15.0-188-generic
*  Database driver: mysql
* Database version: 5.7.37-nmm1-log
* Installed at: all-inkl.com
* Installed Plugins:
   * AddMermaid
   * Auto Email Extended Actions (Not yet tested)
   * AutomaticActionUX  (Not yet tested)
   * Broadcast
   * Chat
   * EmailTaskHistory   (currently does not work?)
   * MarkdownPlus
   * Self-Registration
   * Wiki
* Browser: **SeaMonkey** 2.53.14 Beta pre, Build-Identifikator: 20220801210005  (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)

## STR
1. Close existing Task
   » Will be transferred to Closed Area
   » Expected: I get Email info because I was creator
     Actual: No email   😥

## Additional Info:
a) I see the plugin in the KANBOARD file system (using ftp)
b) In Plugins Dir the plugin still shows "Install"
c) so all as per [forum posting](https://kanboard.discourse.group/t/plugin-directory-plugin-installation/2419)

BTW: I haven't a clue where to modify plugin settings (email recipients, ...). Manual tells nothing.

**Comment by aljawaid** [comment]
Hello, this is an Automatic Action.... did you select and configure from the action list after you have installed the plugin?

**Comment by aljawaid** [comment]
I updated the readme with usage instructions

**Comment by RainerBielefeld** [comment]
I will do a test with the new plugin version, soon
