### ISSUE TITLE
Use Project Email Address as an Email Recipient

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/KanboardEmailHistory#4]
Based on this...

https://kanboard.discourse.group/t/new-action-plugin-kanboardemailhistory/2417/2?u=aljawaid

**Currently:**
Send email to:
- Creator
- Assigned
- Both

**Ideally:**
- Creator
- Assigned
- Project Email
- Creator and Assigned
- All (creator, assigned, project email)

**Comment by aljawaid** [comment]
@creecros how could I call the project email and project identifier in the email?  any ideas?

**Comment by aljawaid** [comment]
@creecros any advice?

**Comment by creecros** [comment]
`use Kanboard\Model\ProjectModel`

`$project = $this->projectModel->getById($project_id);`

now you can use `$project['email']` to get the email of a project.
